name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 * * 1-5'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          DAY=$(date +%A)
          if [ "$DAY" = "Friday" ]; then DAY="weekend"; fi

          echo "Have a nice $DAY!" > README.md

      - name: Commit changes
        run: |
          git config --global user.email "hanscastro@europcar.com"
          git config --global user.name "hanscastroeuropcar"
          git add README.md
          git commit -m "Update README with new message for $DAY"
          git remote set-url origin https://github.com/hanscastroeuropcar/hanscastroeuropcar.git
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
